name: Terraform Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:

    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::8913-7714-9147:role/ec2-admin
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init

      - run: terraform plan

      - run: terraform apply -auto-approve
